### ISSUE TITLE
Integration of Knative does not work 

### ISSUE THREAD

**Issue by Miles-Ahead-Digital** [atomist-blogs/iac-gke#2]
Hi David,
I setup a kubernetes cluster conforming your blog https://blog.atomist.com/kubernetes-ingress-nginx-cert-manager-external-dns/ 
I added istio and use it also instead of the ingress controller. Only the DNS had to be adjusted to be aware of the istio gateway & virtualservices. I works perfect on your cluster settings.

Now I want to use also KNative within the cluster, but it does not work. I could verify that the demo Knative Demo Example works on a "regular" GKE cluster.

There is a perfect iusse description by @skonto https://github.com/knative/serving/issues/10259 but I want to get the infrastructure issue solved (and not knative to handle this situation).  I think it has something to do with authorisation and this topic https://knative.dev/docs/serving/tag-resolution/

Please help me to adjust the Cluster Setting, because I like it very much and everything else is more insecure and not ready for production...

Thanks in advance and best regards
Stefan

**Comment by ddgenome** [comment]
Since this setup disables access to most node metadata from within a pod, https://cloud.google.com/kubernetes-engine/docs/how-to/protecting-cluster-metadata , I would guess this check https://github.com/skonto/serving/blob/debug-stuck-r/vendor/github.com/vdemeester/k8s-pkg-credentialprovider/gcp/metadata.go#L218  is failing. Removing that protection would hinder the security of this setup.

**Comment by Miles-Ahead-Digital** [comment]
Hi David,
thanks for your Reply!
Assuming that there is no change in the check class: What needs to be done on your cluster customizing to enable the Metadata to pass the checks??
Best regards
Stefan

**Comment by ddgenome** [comment]
You might have to disable [GKE Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity), which would require a _lot_ of changes to the code, since it is used to provide external-dns and cert-manager the permissions they need to do their work. Without workload identity, you'd have to assign those capabilities to the nodes, which would mean _any_ pod running would have admin access to your DNS, which would be bad. I think knative needs to fix the issue.

**Comment by Miles-Ahead-Digital** [comment]
Maybe it is possible to create a Service Account with the appropriate authorization and assign it to the gke workload Identity of the knative-serving namespace??

**Comment by ddgenome** [comment]
That might do it, although if that would work it is not clear to me why the endpoint would not return 200 for the query being made.

**Comment by Miles-Ahead-Digital** [comment]
Hi David,

I added the istio and knative namespaces to on of the service account.

The Standard Accounts from the Compute Engine are members. 
Is this the correct approach or what do you propose?

Please refer to the screenshot below

Thanks
Stefan

PS: This setting is not solving the error

![image](https://user-images.githubusercontent.com/58099738/110425589-e29f1380-80a4-11eb-815a-324af66e36b6.png)

**Comment by Miles-Ahead-Digital** [comment]
Hi,

in the knative-serving namespace there are two kubernetes service accounts:  "default" and "controller"
I bound both to the service account running the Nodes: sa-node-prodk8s@prodk8s-cluster.iam.gserviceaccount.com

I followed:
https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#gcloud_1
When I launched the test-pod and run **gcloud auth list** the result was **No credentialed accounts.** (and not the email as expected. But this is the same for the cert-manager service-account (which obviously works).
But launching the knative example still stucks again with RevisionMissing

Is this the right approach? Should the **gcloud auth list** in the "test-pod"? What else do you reccommend?

Thanks
Stefan

**Comment by Miles-Ahead-Digital** [comment]
Hi David,

there is a knative version which support Workload Identity https://github.com/google/knative-gcp 
It is working using your cluster settings with the exception that i omitted the param --enable-private-nodes --master-ipv4-cidr="$mcidr"

If I create the cluster with   --enable-private-nodes --master-ipv4-cidr="$mcidr" the knative istio setup fails.

Error from server (InternalError): error when creating "https://github.com/knative/net-istio/releases/download/v0.21.0/net-istio.yaml": **Internal error occurred: failed calling webhook "config.webhook.serving.knative.dev": Post https://webhook.knative-serving.svc:443/config-validation?timeout=10s: context deadline exceeded**

It seem that internal https traffic fails...due to the fact that the cluster is private now

Do you have any idea how to solve this?

Best regards
Stefan

**Comment by Miles-Ahead-Digital** [comment]
I think it is platform specific and I need to create a firewall rule..
elastic/cloud-on-k8s#1437

I works if I open all ports...I will try to find out which ports must be opened in details..

**Comment by ddgenome** [comment]
The pods should be able to access the GCE metadata endpoint, at least they can without Istio and knative. But it sounds like maybe the metadata endpoint is working with the knative-gcp version.

Regarding the error hitting the webhook.knative-serving.svc endpoint, from the issue you linked to it looks like you need to allow access from the k8s api host to port 9443. The nginx-ingress has a similar requirement for access on port 8443, here is the code used to enable that:

https://github.com/atomist-blogs/iac-gke/blob/734347b009f2c231b60bf2d771d95d408326fd34/index.ts#L239-L257

Just copy and paste that, change the resource name, the port, and update the description and it should work.

**Comment by Miles-Ahead-Digital** [comment]
Hi David,

the root cause is that the GCE metadata endpoint cannot be reached.

I followed these [instructions](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#gcloud_1). This probe is a clear indicator if the problem exists or not.

curl -H 'Metadata-Flavor: Google' 'http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token'
curl: (7) Failed to connect to 169.254.169.254 port 80: Connection timed out

I have no idea how to analyse the error (trace, debug,..) Can you give me a hint how to "repair" it?

In a fresh cluster I got the complete setup working yesterday (your setup + istio + knative  including auto dns and cert integration). The instruction above did work and knative also worked.  But this morning the same error as described above appears also in the "fresh" cluster. The only thing I did was to scale the nodes to 0 overnight.

Uninstalling knative and istio didn't help, but maybe there some leftovers which I did not catch.

I noticed the prometheus-to-sd container in the kube-dns pod crashed with the same error (the same also for the event-exporter-gke pod  - both in the kube system namespace).

The workloads using just istio (and the other components in the infrastructure) are not suffering from this error, but knative is obviously depending on it.  

Any help is appreciated!
Stefan

<img width="671" alt="CleanShot 2021-03-13 at 10 27 21@2x" src="https://user-images.githubusercontent.com/58099738/111025784-ba861c00-83e6-11eb-8e90-bd92fd997494.png">

{
  "insertId": "5tryr7g1zs6su3",
  "jsonPayload": {
    "pid": "1",
    "message": "Failed to get GCE config: error while getting project id: Get http://169.254.169.254/computeMetadata/v1/project/project-id: dial tcp 169.254.169.254:80: i/o timeout"
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "project_id": "prodk8s-cluster",
      "cluster_name": "gke-prodk8s",
      "container_name": "prometheus-to-sd",
      "location": "us-east1-d",
      "pod_name": "kube-dns-69898fd668-47qht",
      "namespace_name": "kube-system"
    }
  },
  "timestamp": "2021-03-13T08:23:13.280290Z",
  "severity": "CRITICAL",
  "labels": {
    "compute.googleapis.com/resource_name": "gke-gke-prodk8s-default-pool-4edcd9a3-zqsd",
    "k8s-pod/k8s-app": "kube-dns",
    "k8s-pod/pod-template-hash": "69898fd668"
  },
  "logName": "projects/prodk8s-cluster/logs/stderr",
  "sourceLocation": {
    "file": "main.go",
    "line": "80"
  },
  "receiveTimestamp": "2021-03-13T08:23:21.014234423Z"
}

**Comment by Miles-Ahead-Digital** [comment]
The same error appear now in my fresh cluster. The only thing I did was to scale the nodes to 0 overnight..
I noticed the prometheus-to-sd container in the kube-dns pod crashed with the same error (the same also for the event-exporter-gke pod  - both in the kube system namespace).

The workloads using just istio (and the other components in the infrastructure) are not suffering from this error, but native is obviously depending on it.  

Any help is appreciated!
Stefan

<img width="671" alt="CleanShot 2021-03-13 at 10 27 21@2x" src="https://user-images.githubusercontent.com/58099738/111025784-ba861c00-83e6-11eb-8e90-bd92fd997494.png">

{
  "insertId": "5tryr7g1zs6su3",
  "jsonPayload": {
    "pid": "1",
    "message": "Failed to get GCE config: error while getting project id: Get http://169.254.169.254/computeMetadata/v1/project/project-id: dial tcp 169.254.169.254:80: i/o timeout"
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "project_id": "prodk8s-cluster",
      "cluster_name": "gke-prodk8s",
      "container_name": "prometheus-to-sd",
      "location": "us-east1-d",
      "pod_name": "kube-dns-69898fd668-47qht",
      "namespace_name": "kube-system"
    }
  },
  "timestamp": "2021-03-13T08:23:13.280290Z",
  "severity": "CRITICAL",
  "labels": {
    "compute.googleapis.com/resource_name": "gke-gke-prodk8s-default-pool-4edcd9a3-zqsd",
    "k8s-pod/k8s-app": "kube-dns",
    "k8s-pod/pod-template-hash": "69898fd668"
  },
  "logName": "projects/prodk8s-cluster/logs/stderr",
  "sourceLocation": {
    "file": "main.go",
    "line": "80"
  },
  "receiveTimestamp": "2021-03-13T08:23:21.014234423Z"
}

**Comment by Miles-Ahead-Digital** [comment]
I rebuild the cluster and tried to reproduce the error be scaling the cluster to 0 and back to 3 nodes.
But right now it still works.. 
The only difference is that I use Kubernetes 1.18.15-gke.1102 (instead of 1.20 before).

I close this message, but I would be happy if you add a procedure how to analyze the error because I have the feeling that it will occur again..

Stefan

**Comment by ddgenome** [comment]
Have you followed these instructions: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#fails ?
